### ISSUE TITLE
Adding https support

### ISSUE THREAD

**Issue by snewell92** [ReactiveX/reactivex.github.io#355] opened 2017-04-19 14:57 UTC
Get free ssl certificates by following [these instructions](https://letsencrypt.org/getting-started/), then set up the cronjob (or equivalent task scheduler) to run the cerbot once or twice a day, and then you have free ssl 5evr, which is one more than forever.

Thanks for reading!

**Comment by snewell92** [comment] 2017-04-19 14:57
This is probably related to #307 - which might be out of date.

**Comment by NZSmartie** [comment] 2017-09-29 04:36
Github pages doesn't support HTTPS for custom domains. (See https://help.github.com/articles/securing-your-github-pages-site-with-https/)
The next best approach is to use a 3rd party like Cloudflare ([Here's a guide](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/))

**Comment by snewell92** [comment] 2017-09-29 13:35
Ah, right you are.

**Comment by preco21** [comment] 2018-05-01 23:57
FYI: I think this could finally be done with [this](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) announcement. GitHub is moving forward to support `https` for custom domains with Let’s Encrypt.

Maybe reopening this issue again?

**Comment by snewell92** [comment] 2018-05-02 12:43
Nice!

**Comment by oboukli** [comment] 2018-06-08 04:52
Any update on this issue?

**Comment by simonbasle** [comment] 2019-03-20 16:06
the HTTPS certificate is still flagged as insecure due to using a certificate delivered to `github.com`.
Maybe `A` DNS records are used? There is a guide on how to configure HTTPS in that later case at https://help.github.com/en/articles/troubleshooting-custom-domains#https-errors

**Comment by oboukli** [comment] 2019-06-20 19:59
To whom it may concern: https://doesmysiteneedhttps.com/

**Comment by crstalli** [comment] 2021-11-01 16:17
So from whois, it looks like @benjchristensen, or at least he should know who does own this domain. We better find out soon because the Registry Expiry Date: 2022-01-04T01:45:54Z is fast approaching.

**Comment by benjchristensen** [comment] 2021-11-02 02:51
I have updated the DNS records and it seems https://reactivex.io is now working. Please verify.

**Comment by akarnokd** [comment] 2021-12-18 14:39
Closing as https://reactivex.io/ is confirmed working. I also enabled "Enforce HTTPS" on the repo and http://reactivex.io should redirect properly.

**Closed by akarnokd** 2021-12-18 14:39 UTC
