### ISSUE TITLE
Please reactivex.io site secured (https).

### ISSUE THREAD

**Issue by dmitry-weirdo** [ReactiveX/reactivex.github.io#389] opened 2019-07-04 12:30 UTC
As we see, http://reactivex.io/ is a non-secure, http site.

One of the inconvenient consequences is that when we try to view a Javadoc in IDEA, the images are not shown (probably because of my company's proxy-server, but anyway), so I have to go to the site in the browser.

It looks like this:
![image](https://user-images.githubusercontent.com/15837869/60666814-4735b400-9e68-11e9-8644-38d9d08cd54c.png)

The suggestion is to make site and links to images in javadocs secured.

**Comment by kennedy** [comment] 2020-04-08 18:03
bump

**Comment by vietj** [comment] 2020-04-16 07:04
bump, this makes javadoc linking from a secure web-site impossible

**Comment by AtosNicoS** [comment] 2021-06-07 10:04
I recently also stumbled across this issue. What a shame that this is still http!

**Comment by ferrata** [comment] 2021-07-08 00:54
Hey folks! Would be awesome to fix this issue.

![image](https://user-images.githubusercontent.com/31716295/124845797-114acf00-df5d-11eb-82da-dc2b3cbe7762.png)

**Comment by r3h0** [comment] 2021-10-09 18:09
Duplicate of #355. See also #398, which indicates that this repo is no longer actively maintained.

**Comment by crstalli** [comment] 2021-11-02 16:06
Https is allowed now; try testing to see if you are still experiencing issues. You can still navigate to the site insecurely, but https is supported now.

**Comment by akarnokd** [comment] 2024-06-05 08:40
Should be working for some time now.

**Closed by akarnokd** 2024-06-05 08:40 UTC
