### ISSUE TITLE
Add HTTPS to  reactivex.io

### ISSUE THREAD

**Issue by a45b** [ReactiveX/reactivex.github.io#409] opened 2021-07-11 18:13 UTC
Can we just add an ssl? LetsEncrypt is there for free. 
Or we can host somewhere which gives it for free like GitHub-pages, netlify, vercel...etc.

**Comment by r3h0** [comment] 2021-10-09 18:08
Duplicate of #355

**Comment by crstalli** [comment] 2021-11-02 16:10
> Duplicate of #355

The site now supports https, although it is not enforced yet.

**Comment by akarnokd** [comment] 2024-06-05 08:32
This started working some time ago so closing as completed.

**Closed by akarnokd** 2024-06-05 08:32 UTC
